### ISSUE TITLE
[建议]请在 Discord 服务器发布服务器版本更新提醒

### ISSUE THREAD

**Issue by Leo204-LKY** [ToreOfficial/CLN#10]
请在 Discord 服务器 `#announcement` 频道发布通知。  
版本更新可参考：  
![image](https://user-images.githubusercontent.com/57821066/91699780-64b6f880-eba7-11ea-965c-36f5108f255d.png)

**Comment by nclmredtea** [comment]
## 收到建议
* 会在下一次版本更新时执行该操作
