### ISSUE TITLE
[BUG/建议]readme.md图片英文错误

### ISSUE THREAD

**Issue by Leo204-LKY** [ToreOfficial/CLN#11]
[![Github状态.png](https://i.postimg.cc/c1g31wx3/Github.png)](https://postimg.cc/vDyT3168)  
`Open Projects`而非`Open Pojects`。  
  
此外，如果你希望图片中的 Open Issues 能自动更新，请使用[Shields.io](https://img.shields.io/)创建图片。  
生成的样式如下：[![GitHub issues](https://img.shields.io/github/issues/nclmredtea/NAHGN)](https://github.com/nclmredtea/NAHGN/issues)  
_点击此图标可跳转至`Issues`页面。_  
Markdown 代码如下：  
```
[![GitHub issues](https://img.shields.io/github/issues/nclmredtea/NAHGN)](https://github.com/nclmredtea/NAHGN/issues)
```
你可以尝试关闭或开启一个 Issue ，查看数字更新。
_请注意，该功能不支持自定义图片。_

**Comment by nclmredtea** [comment]
## 感谢提醒
* 会在下次编辑时修复错误
* Shields.io网站在之前有所研究，但个人认为自己做的图片更加好看，后续可能会在考虑便捷性的时候使用该网站。
### （之前电脑故障，所以回复延迟了）
