### ISSUE TITLE
[BUG]整合包解压后未找到启动器文件等

### ISSUE THREAD

**Issue by Leo204-LKY** [ToreOfficial/CLN#8]
![image](https://user-images.githubusercontent.com/57821066/91699605-1c97d600-eba7-11ea-9d9d-a341ba3f5043.png)

**Comment by nclmredtea** [comment]
## 收到反馈
* 原HMCL和BakeXL启动器转为隐藏文件，现使用UpdateLauncher运行游戏，如需使用原启动器，请打开windows功能“显示隐藏文件”
